name: Bot Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Especifique a versão do Python desejada

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Certifique-se de que requirements.txt está no diretório raiz

      - name: Run the bot
        run: python bot.py  # Substitua pelo nome do seu arquivo principal do bot

      - name: Commit and Push Changes (if applicable)
        run: |
          git config --global user.name "Your Name"
          git config --global user.email "your_email@example.com"
          git add .
          git commit -m "Update from GitHub Actions" || echo "No changes to commit"
          git push
