name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Ou a versão que você preferir

    - name: Install dependencies
      run: |
        pip install -r requirements.txt  # Adicione suas dependências aqui, se houver

    - name: Run tests
      run: |
        python -m unittest discover -s tests  # Ajuste conforme sua estrutura de testes

    - name: Execute slim_ia_data.py
      run: |
        python slim_ia_data.py  # Executa o seu script, ajuste conforme necessário
